name: CI

on:
  pull_request:
  push:

jobs:
  tox:
    name: isolated chatmaild tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # Checkout pull request HEAD commit instead of merge commit
        # Otherwise `test_deployed_state` will be unhappy.
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: run chatmaild tests 
        working-directory: chatmaild
        run: pipx run tox

  scripts:
    name: deploy-chatmail tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: initenv 
        run: scripts/initenv.sh

      - name: append venv/bin to PATH
        run: echo venv/bin >>$GITHUB_PATH

      - name: run formatting checks 
        run: cmdeploy fmt -v 

      - name: run deploy-chatmail offline tests 
        run: pytest --pyargs cmdeploy 

      # all other cmdeploy commands require a staging server 
      # see https://github.com/deltachat/chatmail/issues/100
